name: tech_stack
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_redux: ^0.10.0
  app_kit: 
    git:
        url: https://github.com/KerJen/app_kit.git
  dio: ^4.0.6
  get_it: ^7.2.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  auto_route: ^5.0.4
  auto_route_generator: ^5.0.3
  url_launcher: ^6.1.7
  connectivity_plus: ^3.0.2
  dartx: ^1.1.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  http_status_code: ^0.0.2
  easy_localization: ^3.0.1
  injectable: ^2.1.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  mockito: ^5.3.2
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  injectable_generator: ^2.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
    

